### ISSUE TITLE
Do not migrating on 5.0.4

### ISSUE THREAD

**Issue by qawsed55** [pcx229/redmine_duplicates_of_duplicate_issues#1]
```
rake aborted!
NameError: uninitialized constant ViewsHook
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/opt/redmine/config/environment.rb:16:in `<top (required)>'
/opt/redmine/plugins/issue_recurring/lib/tasks/issue_recurring.rake:8:in `require_relative'
/opt/redmine/plugins/issue_recurring/lib/tasks/issue_recurring.rake:8:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `block in load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/lib/tasks/redmine.rake:218:in `block in <top (required)>'
/opt/redmine/lib/tasks/redmine.rake:218:in `each'
/opt/redmine/lib/tasks/redmine.rake:218:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `block in load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:675:in `block in run_tasks_blocks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:675:in `each'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:675:in `run_tasks_blocks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:528:in `run_tasks_blocks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:464:in `load_tasks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `public_send'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `method_missing'
/opt/redmine/Rakefile:7:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

```

**Comment by pcx229** [comment]
Thanks for bringing this to my attention, this problem was due to a file without a class with the same name inside it, i uploaded a fix for it.
